
server:
  port:  8080
spring:
  redis:
    jedis:
      max:
        total: 100  #jedis 总量
        idle: 50    #空闲jedis 实例最大值
        waitmillis: 500 #当池内没有返回jedis 对象时，最大等待时间
        timeout:  0 #当客户端闲置多长时间后 关闭连接，如果指定为 0,表示连接不会断
      host: 127.0.0.1 #redis 服务ip地址
      port: 6379  #端口
      password:  #密码
      databases: 2