dubbo:
  application:
      name: demo-provider # Dubbo Provider 的名字
  registry:
      # 注册中心地址，即前面启动的Zookeeper地址
      address: zookeeper://127.0.0.1:2181 
  protocol:
      name: dubbo # 指定通信协议
      port: 20880 # 通信端口，这里指的是与消费者间的通信协议与端口
  provider:
      timeout: 10000 # 配置全局调用服务超时时间，dubbo默认是1s，肯定不够用呀
      retries: 0 # 不进行重试
      delay: -1