server:
  port: 8018
spring:
   application:
      name: app-itmayidu-member
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8100/eureka
    register-with-eureka: true
    fetch-registry: true
