server:
  port: 8001
spring:
  application:
    name: app-itmayidu-order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    register-with-eureka: true
    fetch-registry: true
