spring:
  application:
       name: service-zuul
  datasource:
     # type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        username: root
        password: root
server:
  port:  8009
logging:
  level:
    com.taotao.springbootword.mapper: debug