server:
  port: 8100
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
   application:
     name: eureka-server